# Config of ArkaniaStudios-Ange

server-name: Arkania-Test

# english => English
# french => French
default-language: french
console-language: french

database:
  host: '45.145.164.37'
  username: 'ArkaniaStudios-Prod'
  password: '!4Zb2a1x2'
  schema: 'ArkaniaStudios-Prod'
  port: 3306